---
- name: install docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install requirements
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker-ce

- name: install docker-compose_version
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0544

- name: create docker configure directory
  file: path={{ item }} state=directory
  with_items:
    - /etc/docker

- name: just force systemd to reread configs
  systemd: daemon_reload=yes

- name: start and enable docker engine
  systemd:
    name: docker
    state: started
    enabled: yes
